// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLLygAaapmHMG46g2CPriN-2lus6_gGq0',
    appId: '1:1025008332482:web:510e582bc942b7b510155b',
    messagingSenderId: '1025008332482',
    projectId: 'aranias-mexico-app-eb6be',
    authDomain: 'aranias-mexico-app-eb6be.firebaseapp.com',
    storageBucket: 'aranias-mexico-app-eb6be.firebasestorage.app',
    measurementId: 'G-FCT0MBE9GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDx66z0vLTTlRIe1JbufSq_hF59xfzwv4',
    appId: '1:1025008332482:android:9aa8a4d7535968db10155b',
    messagingSenderId: '1025008332482',
    projectId: 'aranias-mexico-app-eb6be',
    storageBucket: 'aranias-mexico-app-eb6be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5nIJIXJOt3JOUbPpQYCcIqh17rpyrPnE',
    appId: '1:1025008332482:ios:09d69ea745b6b84710155b',
    messagingSenderId: '1025008332482',
    projectId: 'aranias-mexico-app-eb6be',
    storageBucket: 'aranias-mexico-app-eb6be.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5nIJIXJOt3JOUbPpQYCcIqh17rpyrPnE',
    appId: '1:1025008332482:ios:09d69ea745b6b84710155b',
    messagingSenderId: '1025008332482',
    projectId: 'aranias-mexico-app-eb6be',
    storageBucket: 'aranias-mexico-app-eb6be.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLLygAaapmHMG46g2CPriN-2lus6_gGq0',
    appId: '1:1025008332482:web:01d4383d6d8fe4fe10155b',
    messagingSenderId: '1025008332482',
    projectId: 'aranias-mexico-app-eb6be',
    authDomain: 'aranias-mexico-app-eb6be.firebaseapp.com',
    storageBucket: 'aranias-mexico-app-eb6be.firebasestorage.app',
    measurementId: 'G-NC7QPEQFGJ',
  );
}
