// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyeuJDpnktztc88DSsnM7y6_jJ3Vg6qZ4',
    appId: '1:795149237250:web:75cdf50d3de3860c9fbb1b',
    messagingSenderId: '795149237250',
    projectId: 'aranias-mexico-app',
    authDomain: 'aranias-mexico-app.firebaseapp.com',
    storageBucket: 'aranias-mexico-app.firebasestorage.app',
    measurementId: 'G-5L7VK8EZVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ex5PyzbE1pF1O4EKvqr9KbiLhYK1Uiw',
    appId: '1:795149237250:android:609f69a584d7168c9fbb1b',
    messagingSenderId: '795149237250',
    projectId: 'aranias-mexico-app',
    storageBucket: 'aranias-mexico-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABQmmgsadVCLNTAtmTDONW7PYW3sGCKH8',
    appId: '1:795149237250:ios:f9f1b1f567c839519fbb1b',
    messagingSenderId: '795149237250',
    projectId: 'aranias-mexico-app',
    storageBucket: 'aranias-mexico-app.firebasestorage.app',
    iosBundleId: 'com.example.segundaTarea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABQmmgsadVCLNTAtmTDONW7PYW3sGCKH8',
    appId: '1:795149237250:ios:f9f1b1f567c839519fbb1b',
    messagingSenderId: '795149237250',
    projectId: 'aranias-mexico-app',
    storageBucket: 'aranias-mexico-app.firebasestorage.app',
    iosBundleId: 'com.example.segundaTarea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyeuJDpnktztc88DSsnM7y6_jJ3Vg6qZ4',
    appId: '1:795149237250:web:2e22180ab4ab647f9fbb1b',
    messagingSenderId: '795149237250',
    projectId: 'aranias-mexico-app',
    authDomain: 'aranias-mexico-app.firebaseapp.com',
    storageBucket: 'aranias-mexico-app.firebasestorage.app',
    measurementId: 'G-YPS82M7K5L',
  );
}
